expr_name: just_work
is_restart: true
ns: 6
nr: 8
nr_back: 8
lb: 1.e-20
n_epoch: 2000
n_plot: 10
grad_max: 1.e2
maxiters: 50000

lr_max: 5.e-4
lr_min: 1.e-5
lr_decay: 0.2
lr_decay_step: 500
w_decay: 1.e-6
